<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IEAM - NodeRed Edge Nodes</title>
     <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="/js/bootstrap.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  
	<link rel="stylesheet" href="/resources/demos/style.css">
	
	<link rel="stylesheet" href="/js/jquery-ui.css">
		
	<script src="/js/jquery-1.12.4.js"></script>
	<script src="/js/jquery-ui.js"></script>
	<script src="/js/jquery.dataTables.min.js"></script>

	<link rel="stylesheet" type="text/css" href="/js/jquery.dataTables.min.css">
	
	<style>
    .overlay{
        display: none;
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        z-index: 999;
        background: rgba(255,255,255,0.8) url("/images/loader.gif") center no-repeat;
		}
    
	body{
        text-align: center;
		}
    
	/* Turn off scrollbar when body element has the loading class */
    body.loading{
        overflow: hidden;   
		}
    
	/* Make spinner image visible when body element has the loading class */
    body.loading .overlay{
        display: block;
		}
	</style>
	
  </head>
  
  <script>
    
	$(document).on({
		
		ajaxStart: function(){
			$("body").addClass("loading"); 
		},
		ajaxStop: function(){ 
			$("body").removeClass("loading"); 
		}    
	});
	
    $(document).ready(function() {
		
		var table = $('#deployments').DataTable( {
            
            data: <?php echo json_encode($data["deployments"]);?>,
            columnDefs: [
                { className: 'dt-left', targets: [0,1] },
                { className: 'dt-center', targets: [2,3,4,5,6] },
				{
				  targets: 7,
				  visible: false
				},
                {
                  targets: 8, 
                  data: null,
                  defaultContent: '<button class="service-open ui-button ui-widget ui-corner-all">Open</button>'
                }
                
              ]
            });
		
		$('.deploy_active').css({"background": "green", "color": "white"});
		
		$('.navbar-brand').on('click', function(evt){
							
			$("body").addClass("loading"); 			   
			//evt.preventDefault(); 
			});
			
		$('.btn').on('click', function(evt){
							
			$("body").addClass("loading"); 			   
			//evt.preventDefault(); 
			});
			
		$('.service-open').each(function () {
	    	$(this).on('click', function(evt){
			   
			   $("body").addClass("loading"); 
			   
			   $this = $(this);		
			   
			   var currentRow = $(this).closest("tr");
			   var data = $('#deployments').DataTable().row(currentRow).data();
				   
			   window.location.href=data[7];
			  
			   evt.preventDefault(); 
		       });
            });
			
		});
  
  </script>
  
  <body style="padding-top: 95px">

	<div class="overlay"></div>
	
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="<?php echo $data['router']->pathFor('home'); ?>">Home </a>
		  <a class="navbar-brand" href="<?php echo $data['router']->pathFor('nodered'); ?>">NodeRed </a>		
		  <a class="navbar-brand" href="<?php echo $data['router']->pathFor('config'); ?>">Configuration </a>
        </nav>
      </div>
    </div>
    
	<!-- content area -->
    <div class="container" style="text-align: center">
    <!--  <p>
        <a role="button" class="btn btn-success" href="www.ibm.com">Add new project</a>
      </p>      
	-->
		<table id="deployments" class="display" style="width:100%">
        <thead>
            <tr>
				<th>ACTIVE</th>
                <th>ID</th>
				<th>Version</th>
				<th>Type</th>
                <th>Description</th>
				<th>Date</th>                     
				<th>Updated</th> 
				<th></th>
				<th></th>
            </tr>
        </thead>
		</table>	
				
    </div>        
    <!-- content area ends-->
    	
    <!-- footer -->
    <div class="container" style="padding-top: 40px">		
		<div class="row">
        <nav class="navbar navbar-expand-md">
          <a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('nodered-deployment-add', array( 'node'=> $data["node"], 'url'=> $data["url"], 'version'=> $data["version"], 'arch'=> $data["arch"]) ); ?>">Add Deployment</a>          		  
        </nav>
      </div>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>