<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IEAM - NodeRed Edge Nodes</title>
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="/js/bootstrap.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  
	<link rel="stylesheet" href="/resources/demos/style.css">
	
	<link rel="stylesheet" href="/js/jquery-ui.css">
		
	<script src="/js/jquery-1.12.4.js"></script>
	<script src="/js/jquery-ui.js"></script>
	<script src="/js/jquery.dataTables.min.js"></script>

	<link rel="stylesheet" type="text/css" href="/js/jquery.dataTables.min.css">
	
	<!--
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
	-->
	
	<style>
    .overlay{
        display: none;
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        z-index: 999;
        background: rgba(255,255,255,0.8) url("/images/loader.gif") center no-repeat;
		}
    
	body{
        text-align: center;
		}
    
	/* Turn off scrollbar when body element has the loading class */
    body.loading{
        overflow: hidden;   
		}
    
	/* Make spinner image visible when body element has the loading class */
    body.loading .overlay{
        display: block;
		}
	</style>
		
  </head>
  
  <script>
	
	$(document).on({
		
		ajaxStart: function(){
			$("body").addClass("loading"); 
		},
		ajaxStop: function(){ 
			$("body").removeClass("loading"); 
		}    
	});
	
    $(document).ready(function() {
		
		$('#target').attr('src','http://'+window.location.hostname+":<?php echo $data['servicePort'];?>");
		
		$('.navbar-brand').on('click', function(evt){
							
			$("body").addClass("loading"); 			   
			//evt.preventDefault(); 
			});
	
		$('.btn').on('click', function(evt){
							
			$("body").addClass("loading"); 			   
			//evt.preventDefault(); 
			});
			
		$( "#activate_deployment" ).click(function(e) {
			
			$("body").addClass("loading"); 	
			
			e.preventDefault();
			$("#controllo").val("SUBMIT");
			$("#activate_from").submit();
			});
		});
	
	
			
  </script>
  
  <body style="padding-top: 95px">
    
	<div class="overlay"></div>
	
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="<?php echo $data['router']->pathFor('home'); ?>">Home </a>
		  <a class="navbar-brand" href="<?php echo $data['router']->pathFor('nodered'); ?>">NodeRed </a>		
		  <a class="navbar-brand" href="<?php echo $data['router']->pathFor('config'); ?>">Configuration </a>		  
        </nav>
      </div>
    </div>
    
	<!-- content area -->
    <div class="container" style="text-align: center; max-width: 100%; height: 100vh; ">
      
	  <table style="text-align: center; width: 100%">
	  <tr>
	  <td>
	  <p>
		<form id="activate_from" enctype="multipart/form-data" method="post" action="<?php echo $data['router']->pathFor('nodered-deployment-activate', array('node' => $data["node"], 'url'=> $data["url"], 'version'=> $data["version"], 'arch'=> $data["arch"] ) ); ?>">
			
			<input type=hidden name="controllo" id="controllo" value=""> 
			
			<input type=hidden name="object_id" id="object_id" value="<?php echo $object_id;?>">
			<input type=hidden name="object_type" id="object_type" value="<?php echo "deployment-".$data["node"]."_".$data["url"]."_".$data["version"]."_".$data["arch"];?>">
			
			<a role="button" class="btn btn-success" id="activate_deployment" href="#">DEPLOY TO NODE <?php echo $data['node'];?></a>              
			<!--<a id="deploy" role="button" class="btn btn-success" href="www.ibm.com">ACTIVATE TO NODE</a>      -->
			<a role="button" class="btn btn-danger" href="<?php echo $data['router']->pathFor('nodered-data', array( 'node' => $data['node'], 'url' => $data["url"], 'version' => $data["version"], 'arch' => $data["arch"] ) );?>">CANCEL</a>

		</form>
		
		
      </p>      
	  
	  </td>
	  </tr>	  
	  </table>
	  
	  <iframe id="target" style="width:100%; height:80%;" title="NodeRed Build Instance"> 	  
    </div>        
    <!-- content area ends-->
    	
    <!-- footer -->
    <div class="container" style="padding-top: 40px">		
		<div class="row">
        
      </div>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>