<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IEAM - NodeRed Edge Nodes</title>
     <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="/js/bootstrap.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->  
	<link rel="stylesheet" href="/resources/demos/style.css">
	
	<link rel="stylesheet" href="/js/jquery-ui.css">
		
	<script src="/js/jquery-1.12.4.js"></script>
	<script src="/js/jquery-ui.js"></script>
	<script src="/js/jquery.dataTables.min.js"></script>

	<link rel="stylesheet" type="text/css" href="/js/jquery.dataTables.min.css">	
	<!-- FORM STYLE -->
	<style>
	  
		* {
		  box-sizing: border-box;
		}

		input[type=text], select, textarea {
		  width: 100%;
		  padding: 12px;
		  border: 1px solid #ccc;
		  border-radius: 4px;
		  resize: vertical;
		}

		label {
		  padding: 12px 12px 12px 0;
		  display: inline-block;
		}

		input[type=submit] {
		  background-color: #4CAF50;
		  color: white;
		  padding: 12px 20px;
		  border: none;
		  border-radius: 4px;
		  cursor: pointer;
		  float: right;
		}

		input[type=submit]:hover {
		  background-color: #45a049;
		}

		.container_form {
		  border-radius: 5px;
		  background-color: #f2f2f2;
		  padding: 20px;
		}

		.col-25 {
		  float: left;
		  width: 25%;
		  margin-top: 6px;
		}

		.col-75 {
		  float: left;
		  width: 75%;
		  margin-top: 6px;
		}

		/* Clear floats after the columns */
		.row:after {
		  content: "";
		  display: table;
		  clear: both;
		}
		
		.row {
		  padding-right: 20px;
		}

		/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
		@media screen and (max-width: 600px) {
		  .col-25, .col-75, input[type=submit] {
			width: 100%;
			margin-top: 0;
		  }
		}
	 </style>
	 
	<style>
    .overlay{
        display: none;
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        z-index: 999;
        background: rgba(255,255,255,0.8) url("/images/loader.gif") center no-repeat;
		}
    
	body{
        text-align: center;
		}
    
	/* Turn off scrollbar when body element has the loading class */
    body.loading{
        overflow: hidden;   
		}
    
	/* Make spinner image visible when body element has the loading class */
    body.loading .overlay{
        display: block;
		}
	</style>
	
  </head>
      
  <script>
    
	$(document).on({
		
		ajaxStart: function(){
			$("body").addClass("loading"); 
		},
		ajaxStop: function(){ 
			$("body").removeClass("loading"); 
		}    
	});
	
    $(document).ready(function() {
		
		$('.navbar-brand').on('click', function(evt){
							
			$("body").addClass("loading"); 			   
			//evt.preventDefault(); 
			});
			
		});
  </script>
  
  <body style="padding-top: 95px">
	
	<div class="overlay"></div>
	
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="#">Home </a>
		  <a class="navbar-brand" href="<?php echo $data['router']->pathFor('nodered'); ?>">NodeRed </a>
		  <a class="navbar-brand" href="<?php echo $data['router']->pathFor('config'); ?>">Configuration </a>
        </nav>
      </div>
    </div>
    
	<!-- content area -->
    <div class="container" style="text-align: center">
   	
		<div class="container">
			<div class="alert alert-success" role="alert">
				<table style="width: 100%">
				<tr>
				<td>
				<strong><?php echo $data["title"];?></strong> <?php echo $data["message"];?> 
				</td>
				</tr>
				<tr>
				<td>
				<a role="button" class="btn btn-success" href="<?php echo $data['router']->pathFor('home'); ?>">Back</a>
				</td>
				</tr>
				</table>
			</div>
		</div>        
		
    </div>        
    <!-- content area ends-->
      
    <!-- footer -->
    <div class="container">
      <p class="text-center">
        <a href="www.footer.com" role="button" class="btn btn-default btn">Info</a>
      </p>
    </div> 
    <!-- footer ends -->

     
  </body>
</html>